### ISSUE TITLE
Module 'init' could not be found (Windows)

### ISSUE THREAD

**Issue by bearloga** [sony/nnabla-ext-cuda#1]
I'm using Anaconda and following [instructions for installing on Windows](https://nnabla.readthedocs.io/en/latest/python/install_on_windows.html).

**Note**: on Windows, you must `conda install -c anaconda pywin32` for either version to work. This should be noted on the docs. Otherwise you get "no module named win32com.shell" error when you try to `import nnabla`

The CPU version loads and I have CUDA/cuDNN working (I use the GPU version of TensorFlow on the same machine but in a different environment), but when I try to `import nnabla_ext.cuda.cudnn`:

![Screenshot of ImportError](https://user-images.githubusercontent.com/1807519/27570318-22c020f2-5ab2-11e7-897d-1f5d393c8c56.png)

```python
from init import (...
# ImportError: DLL load failed: The specified module could not be found.
```

I think there's a dependency missing. I did notice that there is [an init package](https://pypi.python.org/pypi/init/) out there, but I don't know if that's actually the one that the developers are using here. (Otherwise I would have made a PR for it.)

**Comment by YoshiyukiKobayashi** [comment]
It is probably due to the lack of dependent libraries as you mentioned.
Can you confirm that the following dependencies are installed?

* CUDA 8.0
https://developer.nvidia.com/cuda-downloads
Make sure "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin" is in PATH system environment variable.

* cuDNN 6.0
https://developer.nvidia.com/cudnn
Make sure cudnn64_6.dll is in "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin".

* Microsoft Visual C++ 2015 Redistributable
https://www.microsoft.com/en-us/download/details.aspx?id=52685

"init" is located in the following location, and it is not dependent library.
https://github.com/sony/nnabla-ext-cuda/blob/master/python/src/nnabla_ext/cuda/init.pyx

**Comment by bearloga** [comment]
Hi! The issue was definitely the missing cudnn64_6.dll from CUDA's bin directory! Thank you!

I was trying to point my PATH to it like the way I have TensorFlow set up with cuDNN 5.1. I added "C:\cudnn-8.0-windows10-x64-v5.1\bin" (where my cudnn64_5.dll is) to my PATH and that works for TF. I did the same for cuDNN 6.0 hoping it would work for nnabla but it just wasn't getting recognized until I added the DLL to the CUDA's bin directory like you recommended.

Things seem to work fine now! Although I do get this weird issue at the end of the example:

![untitled-1](https://user-images.githubusercontent.com/1807519/27758563-2bc6c684-5dcc-11e7-8626-77b0e2215abf.png)

But that's possibly a separate issue if I keep seeing it with other examples :)

Thanks! Congratulations on the public release!
